services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking-room-hotel
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: booking-room-hotel
      PORT: 3000

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
